# Site settings
title: Guillaume Wilemme
description: Research economist
#url: "https://gwilemme.github.io" # the base hostname & protocol for your site

# Build settings
theme: minimal
plugins: 
- jekyll-remote-theme 

# Navigation links
#nav:
 # - text: Home
  #  url: /

# Permalinks
#permalink: /home


