# Site settings
title: Guillaume Wilemme
description: Research economist
#url: "https://gwilemme.github.io" # the base hostname & protocol for your site

# Build settings
theme: no-style-please #jekyll-theme-cayman # Change this to the theme you're using, if any
#plugins: [] # Add any plugins you want to use here

# Navigation links
#nav:
 # - text: Home
  #  url: /

# Permalinks
#permalink: /home


